//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CallTime.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О нас.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительные услуги.
        /// </summary>
        public static string AdditionalServices {
            get {
                return ResourceManager.GetString("AdditionalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стать нашим партнером.
        /// </summary>
        public static string BecomeOurPartner {
            get {
                return ResourceManager.GetString("BecomeOurPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало маркетинговой компании.
        /// </summary>
        public static string BeginningMarketingCompany {
            get {
                return ResourceManager.GetString("BeginningMarketingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало переговоров с биржами.
        /// </summary>
        public static string BeginningNegotiationsWithExchanges {
            get {
                return ResourceManager.GetString("BeginningNegotiationsWithExchanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бендеры, Ленина 6.
        /// </summary>
        public static string BenderLenin {
            get {
                return ResourceManager.GetString("BenderLenin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будьте уверены, что обращаетесь к профессионалам своего дела.
        /// </summary>
        public static string BeSureApplyingProfessionals {
            get {
                return ResourceManager.GetString("BeSureApplyingProfessionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рождение идеи.
        /// </summary>
        public static string BirthIdea {
            get {
                return ResourceManager.GetString("BirthIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bounty компания.
        /// </summary>
        public static string BountyCompany {
            get {
                return ResourceManager.GetString("BountyCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Call-центр.
        /// </summary>
        public static string CallCenter {
            get {
                return ResourceManager.GetString("CallCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Call-центров.
        /// </summary>
        public static string CallCenters {
            get {
                return ResourceManager.GetString("CallCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компания (необязательно).
        /// </summary>
        public static string CompanyOptional {
            get {
                return ResourceManager.GetString("CompanyOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заключение договора на обслуживание с первой биржей.
        /// </summary>
        public static string ConclusionServiceWithFirstExchange {
            get {
                return ResourceManager.GetString("ConclusionServiceWithFirstExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связаться с нами.
        /// </summary>
        public static string ConnectWithUs {
            get {
                return ResourceManager.GetString("ConnectWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание токена и обучение персонала.
        /// </summary>
        public static string CreatingTokenTrainingStaff {
            get {
                return ResourceManager.GetString("CreatingTokenTrainingStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на криптовалютными биржами.
        /// </summary>
        public static string CryptoExchange {
            get {
                return ResourceManager.GetString("CryptoExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru.
        /// </summary>
        public static string CurrentLang {
            get {
                return ResourceManager.GetString("CurrentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Развитие.
        /// </summary>
        public static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дневстровск, ул. Строителей 5.
        /// </summary>
        public static string DnestrovskStroiteley {
            get {
                return ResourceManager.GetString("DnestrovskStroiteley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электронный адрес.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Факты и цифры.
        /// </summary>
        public static string FactsAndFigures {
            get {
                return ResourceManager.GetString("FactsAndFigures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма обратной связи.
        /// </summary>
        public static string FeedbackForm {
            get {
                return ResourceManager.GetString("FeedbackForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на для.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получите консультацию по телефону или заходите к нам.
        /// </summary>
        public static string GetAdviceByPhoneOrVisit {
            get {
                return ResourceManager.GetString("GetAdviceByPhoneOrVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Входящие услуги.
        /// </summary>
        public static string InboundServices {
            get {
                return ResourceManager.GetString("InboundServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Первоначальное размещение на бирже.
        /// </summary>
        public static string InitialPlacementExchange {
            get {
                return ResourceManager.GetString("InitialPlacementExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вакансии.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на en.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст вашего сообщения.
        /// </summary>
        public static string MessageText {
            get {
                return ResourceManager.GetString("MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не нашли ответ на нужный вопрос? Напишите нам.
        /// </summary>
        public static string NotFindAnswerToQuestion {
            get {
                return ResourceManager.GetString("NotFindAnswerToQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предложение нашей компании.
        /// </summary>
        public static string OfferOfOurCompany {
            get {
                return ResourceManager.GetString("OfferOfOurCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На карте.
        /// </summary>
        public static string OnMap {
            get {
                return ResourceManager.GetString("OnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходящие услуги.
        /// </summary>
        public static string OutboundServices {
            get {
                return ResourceManager.GetString("OutboundServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Личный кабинет.
        /// </summary>
        public static string PersonalArea {
            get {
                return ResourceManager.GetString("PersonalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проблемы.
        /// </summary>
        public static string Problems {
            get {
                return ResourceManager.GetString("Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Квартал.
        /// </summary>
        public static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предложение.
        /// </summary>
        public static string Sentence {
            get {
                return ResourceManager.GetString("Sentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуги.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обслуживание более 10 бирж.
        /// </summary>
        public static string ServingMore10Exchanges {
            get {
                return ResourceManager.GetString("ServingMore10Exchanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стремимся.
        /// </summary>
        public static string StriveTo {
            get {
                return ResourceManager.GetString("StriveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Субподряд.
        /// </summary>
        public static string Subcontract {
            get {
                return ResourceManager.GetString("Subcontract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подписаться.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подпишись и мы оповестим тебя о развитии нашего проекта.
        /// </summary>
        public static string SubscribeAndWeNotifyYou {
            get {
                return ResourceManager.GetString("SubscribeAndWeNotifyYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подписка.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поддержка сторонних блокчейн проектов и стартапов.
        /// </summary>
        public static string SupportForProjectsStartups {
            get {
                return ResourceManager.GetString("SupportForProjectsStartups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тирасполь, Одесская 86\1.
        /// </summary>
        public static string TiraspolOdessa {
            get {
                return ResourceManager.GetString("TiraspolOdessa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Токен.
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вконтакте.
        /// </summary>
        public static string Vk {
            get {
                return ResourceManager.GetString("Vk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на с.
        /// </summary>
        public static string With {
            get {
                return ResourceManager.GetString("With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваше имя, например Иван.
        /// </summary>
        public static string YourNameEx {
            get {
                return ResourceManager.GetString("YourNameEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваши персональные данные не будут переданы третьим лицам и остануться строго конфидициональны..
        /// </summary>
        public static string YourPersonalDataNotBeTransferred {
            get {
                return ResourceManager.GetString("YourPersonalDataNotBeTransferred", resourceCulture);
            }
        }
    }
}
